name: 'Dependabot Multiple Dependencies Updater'
description: 'Update several dependencies at once'
inputs:
  username:
    description: 'Username to authenticate the request'
    required: true
  repo-token:
    description: 'Token/password to authenticate the request'
    required: true
  repository:
    description: 'Full name of the GitHub repo you want to create pull requests for'
    required: true
  directory:
    description: 'Directory where the base dependency files are'
    required: true
    default: "/"
  package-manager:
    description: 'Package manager'
    required: true
    default: "pip"
  batch-size:
    description: 'Batch size'
    required: true
    default: "5"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.repo-token }}
    - ${{ inputs.repository }}
    - ${{ inputs.directory }}
    - ${{ inputs.package-manager }}
    - ${{ inputs.batch-size }}
